### ISSUE TITLE
Automation issue: Output vs Input Slots not recognized

### ISSUE THREAD

**Issue by oliverkane** [oierbravo/createsifter#30]
Unlike the very similar Millstone, this block doesn't seem to work well with automation devices. Eg: if you have a millstone, you can put a chute below it and the products will be exported when they're done. However, if you do this with the Sifter, it will export it's feedstock right away, effectively making automation very difficult.

Is this intentional?  Is there another way to make this work as intended?  I've been playing Create Astral, and can provide more details if needed.

**Comment by ZeekDaGeek** [comment]
Having the same exact issue. Not usually a problem when filtered input/output is possible in vanilla Create but in Astral in order to get Brass for filterable chutes you need to visit different planets, which is hours in.

Illustration of the issue.
![kFjgt](https://github.com/oierbravo/createsifter/assets/1709288/b0cfa0fb-6027-4088-9386-1e329c037a19)


Dealing with the bug in the mean time:
![image](https://github.com/oierbravo/createsifter/assets/1709288/6f3dc66d-3727-4ea0-943d-b24aec233edd)

Each storage unit is filtered to extract only output items with the configure slots UI.

**Comment by oliverkane** [comment]
Oh cool. I didn't know those storage units could be configured. That'll do!

**Comment by oierbravo** [comment]
Sorry, but Create Astral uses the fabric port, not this mod.

I'll leave the issue open for others with the same or similar problems.

**Comment by oliverkane** [comment]
Ah, I didn't even realize there was such a distinction.  Just getting to learn all things Fabric.  This is why I get for taking a snooze since the 1.7.10 days. I'll continue my search.  

Thanks for keeping this open!
